### PR TITLE
Empty translation file crash

### LINKED ISSUE #3: Empty translation file crash
For some many and various reasons, a project can contain an empty translation file.
The yml parser return a null instead of an empty array which may cause this:

```
➜  translation-server git:(master) ✗ php build/translation-server.phar translation:server:view

[Trans Server] Command started at Wed, 28 Oct 2015 
PHP Catchable fatal error:  Argument 3 passed to Mmoreram\TranslationServer\Model\Repository::createPlainRepresentationByArray() must be of the type array, null given, called in phar:///Users/xxx/Sites/vhosts/xxxx.loc/translation-server/build/translation-server.phar/src/TranslationServer/Model/Repository.php on line 110 and defined in phar:///Users/xxxx/Sites/vhosts/xxxx.loc/translation-server/build/translation-server.phar/src/TranslationServer/Model/Repository.php on line 154
```

### PR DESCRIPTION
**Pull request by ScullWM**
See #3

### CODE REVIEW

File: src/TranslationServer/Model/Repository.php [hunk 1]
```diff
@@ -105,7 +105,7 @@ public static function createByFilePath($filepath)
         self::createPlainRepresentationByArray(
             $translations,
             $language,
-            $data,
+            ($data) ? $data : [],
```
Comment (mmoreram) [inline src/TranslationServer/Model/Repository.php]: This is equals than `$data ?: []` :)

Comment (ScullWM) [inline src/TranslationServer/Model/Repository.php]: Yes I've start with a is_array($data) in case of data was a string, but i'ts not possible.
Will fix it

**Comment by mmoreram** [comment]
Thanks @ScullWM :)
